name: NayolaPerms
version: '${project.version}'
author: Markus Peirleitner (Rengobli)
website: www.peirleitner.at
api-version: 1.19
depend: [LocalCore]

main: at.peirleitner.nayolaperms.NayolaPerms

commands:
  nayolaperms:
    usage: </command>
    description: Permission Management
    aliases: [np]
  rank:
    usage: </command>
    description: Current rank information
    aliases: [rang, perm, permission, group]
  groups:
    usage: </command>
    description: List all existing groups
    aliases: [ranks]