name: NayolaPerms
version: '${project.version}'
author: Markus Peirleitner (Rengobli)
website: [www.peirleitner.at, www.nayola.net]
api-version: 1.19
depend: [NayolaCoreSpigot]

main: net.nayola.nayolaperms.NayolaPerms

commands:
  nayolaperms:
    usage: </command>
    description: Permission Management
    aliases: [np]
  rank:
    usage: </command>
    description: Current rank information
    aliases: [rang, perm, permission, group]